version: 2.1

#orbs
orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.8.2
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: echo "Run tests..."
          npm run test
  publish:
    executor: docker/docker
    steps: -setup_remote_docker
      -checkout
      -docker/check
    -docker/build: #builds the image similar to docker build -t <image_name> .
      image: practiceimage
      tag: v1.0.2
    -docker/push: #pushes image to the specified account in enviromental variable
      image: practiceimage
      tag: v1.0.2
# Orchestrate our job run sequence WORKFLOWS
workflows:
  simple-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
